/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ListLazyImport = createFileRoute('/list')()
const IndexLazyImport = createFileRoute('/')()
const ActionNewLazyImport = createFileRoute('/action/new')()

// Create/Update Routes

const ListLazyRoute = ListLazyImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/list.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ActionNewLazyRoute = ActionNewLazyImport.update({
  id: '/action/new',
  path: '/action/new',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/action/new.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListLazyImport
      parentRoute: typeof rootRoute
    }
    '/action/new': {
      id: '/action/new'
      path: '/action/new'
      fullPath: '/action/new'
      preLoaderRoute: typeof ActionNewLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/list': typeof ListLazyRoute
  '/action/new': typeof ActionNewLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/list': typeof ListLazyRoute
  '/action/new': typeof ActionNewLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/list': typeof ListLazyRoute
  '/action/new': typeof ActionNewLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/list' | '/action/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/list' | '/action/new'
  id: '__root__' | '/' | '/list' | '/action/new'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ListLazyRoute: typeof ListLazyRoute
  ActionNewLazyRoute: typeof ActionNewLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ListLazyRoute: ListLazyRoute,
  ActionNewLazyRoute: ActionNewLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/list",
        "/action/new"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/list": {
      "filePath": "list.lazy.tsx"
    },
    "/action/new": {
      "filePath": "action/new.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
